# Generated by Django 4.0.4 on 2022-06-19 06:56

# 3rd-party
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_alter_searchimage_uploaded_image"),
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="wishlist_activities",
            field=models.ManyToManyField(related_name="wishlist_activities", to="search.activity"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="wishlist_events",
            field=models.ManyToManyField(related_name="wishlist_events", to="search.event"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="wishlist_places",
            field=models.ManyToManyField(related_name="wishlist_places", to="search.place"),
        ),
    ]
