version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@3.0.0

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          DJANGO_SECRET_KEY: test_django_secret_key
          DEBUG: False
          POSTGRES_DB_NAME: my_memory_maker
          POSTGRES_DB_USER: my_memory_maker
          POSTGRES_DB_PASSWORD: my_memory_maker
          POSTGRES_DB_HOST: localhost
          POSTGRES_DB_PORT: 5432
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: my_memory_maker
          POSTGRES_PASSWORD: my_memory_maker
          POSTGRES_DB: my_memory_maker
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/development.txt
      - run:
          name: Run tests
          command: |
            pytest . --cov=search users --cov-report=xml --ds=my_memory_maker.settings.test
      - run:
          name: Black
          command: |
            black -l 100 --check my_memory_maker users search
      - run:
          name: Flake8
          command: |
            flake8 my_memory_maker users search
      - codecov/upload