# Generated by Django 4.0.4 on 2022-06-03 11:10

# 3rd-party
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbriteraweventdata",
            name="data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
