# Generated by Django 4.0.4 on 2022-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_eventbriteeventid_first_fetched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBriteImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=500)),
                ('error_message', models.TextField()),
                ('important_args', models.JSONField()),
            ],
        ),
    ]
