# Generated by Django 4.0.4 on 2022-06-21 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_eventbriteimporterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbriteraweventdata',
            name='last_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
