# Generated by Django 4.0.4 on 2022-06-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_eventbriteraweventdata_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbriteraweventdata',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.eventbriteeventid', unique=True),
        ),
    ]
