# Generated by Django 4.0.4 on 2022-06-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_eventbriteraweventdata_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbriteraweventdata',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.eventbriteeventid'),
        ),
    ]
