# Generated by Django 4.0.4 on 2022-05-06 09:20

# Standard Library
import uuid

# 3rd-party
import django.contrib.postgres.fields
from django.contrib.postgres.operations import HStoreExtension
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now=True)),
                ("approval_timestamp", models.DateTimeField(null=True)),
                ("headline", models.CharField(max_length=2048)),
                ("description", models.TextField()),
                ("price_lower", models.FloatField()),
                ("price_upper", models.FloatField()),
                ("duration_lower", models.IntegerField()),
                ("duration_upper", models.IntegerField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manually_added", "manually_added")],
                        max_length=256,
                        verbose_name="Source of entity.",
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        null=True, verbose_name="Pseudo-FK to the source data table (if any)"
                    ),
                ),
                ("attributes", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("uploaded_timestamp", models.DateTimeField(auto_now=True)),
                ("s3_key", models.CharField(max_length=2048, null=True)),
                ("link_url", models.CharField(max_length=2048, null=True)),
                ("alt_text", models.CharField(max_length=2048)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now=True)),
                ("approval_timestamp", models.DateTimeField(null=True)),
                ("headline", models.CharField(max_length=2048)),
                ("description", models.TextField()),
                ("price_lower", models.FloatField()),
                ("price_upper", models.FloatField()),
                ("duration_lower", models.IntegerField()),
                ("duration_upper", models.IntegerField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manually_added", "manually_added")],
                        max_length=256,
                        verbose_name="Source of entity.",
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        null=True, verbose_name="Pseudo-FK to the source data table (if any)"
                    ),
                ),
                ("attributes", django.contrib.postgres.fields.hstore.HStoreField()),
                ("google_maps_place_id", models.CharField(max_length=1024, null=True)),
                ("activities", models.ManyToManyField(to="search.activity")),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("images", models.ManyToManyField(to="search.searchimage")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(auto_now=True)),
                ("approval_timestamp", models.DateTimeField(null=True)),
                ("headline", models.CharField(max_length=2048)),
                ("description", models.TextField()),
                ("price_lower", models.FloatField()),
                ("price_upper", models.FloatField()),
                ("duration_lower", models.IntegerField()),
                ("duration_upper", models.IntegerField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manually_added", "manually_added")],
                        max_length=256,
                        verbose_name="Source of entity.",
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        null=True, verbose_name="Pseudo-FK to the source data table (if any)"
                    ),
                ),
                ("attributes", django.contrib.postgres.fields.hstore.HStoreField()),
                (
                    "dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.DateTimeField(), size=2
                        ),
                        size=None,
                        verbose_name="Event dates",
                    ),
                ),
                ("activities", models.ManyToManyField(to="search.activity")),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("images", models.ManyToManyField(to="search.searchimage")),
                ("places", models.ManyToManyField(to="search.place")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="images",
            field=models.ManyToManyField(to="search.searchimage"),
        ),
    ]
