# Generated by Django 4.0.4 on 2022-05-18 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='source_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Pseudo-FK to the source data table (if any)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Pseudo-FK to the source data table (if any)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='source_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Pseudo-FK to the source data table (if any)'),
        ),
    ]
