# Generated by Django 4.0.4 on 2022-05-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_make_fields_blankable'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location_lat',
            field=models.FloatField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='location_long',
            field=models.FloatField(max_length=40, null=True),
        ),
    ]
