# Generated by Django 4.0.4 on 2022-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_place_location_lat_place_location_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
