# Generated by Django 4.0.4 on 2022-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_activity_source_type_alter_event_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Pseudo-FK to the source data table (if any)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Pseudo-FK to the source data table (if any)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='source_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Pseudo-FK to the source data table (if any)'),
        ),
    ]
